apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test
  namespace: default
  labels:
    app: test
spec:
  accessModes: [ "ReadWriteOnce" ]
  storageClassName: nfs-storageclass
  resources:
    requests:
      storage: "10Gi"
